name = "pamdingal"
compatibility_date = "2025-04-01"

main = "worker/index.js"

assets = { directory = "." }

[vars]
CONTACT_EMAIL = "pamdingal@apiis.org"

[[d1_databases]]
binding       = "DB"
database_name = "pamdingal-contacts"
database_id   = "ce0988c6-a18e-46d6-a0da-36d0d796fe80"
